project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Migrations"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/placeholder.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
